window.ESCUDOS_BASE_PATH = "../imagens/";

window.escudosTimes = {
  "cartola scheuer17": "../imagens/1_cartola_scheuer17.png",
  "Dom Camillo68": "../imagens/1_dom_camillo68.png",
  "FBC Colorado": "../imagens/1_fbc_colorado.png",
  "Fedato Futebol Clube": "../imagens/1_fedato_futebol_clube.png",
  "Gremiomaniasm": "../imagens/1_gremiomaniasm.png",
  "JV5 Tricolor Gaúcho": "../imagens/1_jv5_tricolor_gaucho.png",
  "MAFRA MARTINS FC": "../imagens/1_mafra_martins_fc.png",
  "Mau Humor F.C.": "../imagens/1_mauhumor_fc.png",
  "Paulo Virgili FC": "../imagens/1_paulo_virgili_fc.png",
  "pura bucha/internacional": "../imagens/1_pura_bucha_internacional.png",
  "seralex": "../imagens/1_seralex.png",
  "TEAM LOPES 99": "../imagens/1_team_lopes_99.png",
  "Texas Club 2026": "../imagens/1_texas_club_2026.png",
  "TIGRE LEON": "../imagens/1_tigre_leon.png",
  "TORRESMO COM PINGA PRO26.2": "../imagens/1_torresmo_com_pinga_pro262.png",
  "VASCO MARTINS FC": "../imagens/1_vasco_martins_fc.png",
  "A Lenda Super Vasco F.c": "../imagens/1_a_lenda_super_vasco_fc.png",
  "CAFÉ AMARGO PRO26.2": "../imagens/1_cafe_amargo_pro262.png",
  "mercearia Estrela": "../imagens/1_mercearia_estrela.png",
  "pra sempre imortal fc": "../imagens/1_pra_sempre_imortal_fc.png",
  "TATITTA FC": "../imagens/1_tatitta_fc.png",
  "Pity10": "../imagens/1_pity10.png",
  "PUXE FC": "../imagens/1_puxe_fc.png",
  "Sport Clube PAIM": "../imagens/1_sport_clube_paim.png",
  "C R Juvenal": "../imagens/1_c_r_juvenal_fc.png",
  "GE Bebum": "../imagens/1_ge_bebums_fc.png",
  "lsauer fc": "../imagens/1_lsauer_fc.png",
  "SC ÉoINTER!": "../imagens/1_sc_eointer.png",
  "A Lenda Super Vascão f.c": "../imagens/1_super_vascao_fc.png",
  "AZURRA82": "../imagens/1_azurra82.png",
  "Bandoleros FCS": "../imagens/1_bandoleros_fcs.png",
  "BordonFC04": "../imagens/1_bordonfc04.png",
  "C.A. Charru@": "../imagens/1_ca_charrua.png",
  "CARTOLEIRO DO VALLE PRO26.5": "../imagens/1_cartoleiro_do_valle_pro265.png",
  "dasdoresfc": "../imagens/1_dasdoresfc.png",
  "DM Studio": "../imagens/1_dm_studio.png",
  "FBC Colorado II": "../imagens/1_fbc_colorado_II.png",
  "FIGUEIRA DA ILHA": "../imagens/1_figueira_da_ilha.png",
  "Gig@ntte": "../imagens/1_gigntte.png",
  "Grêmio imortal 37": "../imagens/1_gremio_imortal_37.png",
  "JUV. KP": "../imagens/1_juv_kp.png",
  "Luis lemes inter": "../imagens/1_luis_lemes_inter.png",
  "Máquina Laranjja": "../imagens/1_maquina_laranjja.png",
  "Rolo Compressor ZN": "../imagens/1_rolo_compressor_zn.png",
  "Super Vasco f.c": "../imagens/1_super_vasco_fc.png",
  "SUPER VASCÃO F.C": "../imagens/1_super_vascao_fc.png",
  "Tabajara de Inhaua PB1": "../imagens/1_tabajara_de_inhaua_pb1.png",
  "Tatols Beants F.C": "../imagens/1_tatols_beants_fc.png",
  "teves_futsal20 f.c": "../imagens/1_teves_futsal20_fc.png",
  "Time do S.A.P.O": "../imagens/1_time_do_sapo.png",
  "La Primeira Patada Es Nuestra": "../imagens/1_la_primeira_patada_es_nuestra.png",
  "bugredasmissões": "../imagens/1_bugredasmissoes.png",
  "Medonho´s F.C.": "../imagens/1_medonhos_fc.png",
  "NHU PORÃ SAF.": "../imagens/1_nhu_pora_saf.png", 
  "LISI GREMISTA": "../imagens/1_lisi_gremista.png",
  "BORGES ITAQUI F.C.": "../imagens/1_borges_itaqui_fc.png",
  "FÚRIA LEON": "../imagens/1_furia_leon.png",
  "KillerColorado": "../imagens/1_killercolorado.png",
  "TORRESMO COM PINGA PRO26.1": "../imagens/1_torresmo_com_pinga_pro261.png",
  "Tabajara de Inhaua PB1": "../imagens/1_tabajara_de_inhaua_pb1.png",
  "Super Vasco f.c": "../imagens/1_super_vasco_fc.png",
  "S.E.R. GRILLO": "../imagens/1_ser_grillo.png",
  "SERGRILLO": "../imagens/1_sergrillo.png",
  "NaoVaiDescer!": "../imagens/1_naovaidescer.png",
  "Atlético Colorado 2021": "../imagens/1_atletico_colorado_2021.png",
  "BORGES CLIMA FUT F.C": "../imagens/1_borges_clima_fut_fc.png",
  "FC castelo Branco 2": "../imagens/1_fc_castelo_branco_2.png",
  "FC Los Castilho": "../imagens/1_fc_los_castilho.png",  
  "Profit Soccer": "../imagens/1_profit_soccer.png",
  "Atlético Colorado 2021": "../imagens/1_atletico_colorado_2021.png",
  "Doug Leal F.C": "../imagens/1_doug_leal_fc.png",
  "Grêmio_Campeão_LA_27": "../imagens/1_gremio_campeao_la_27.png",
  "Esquadrão Gazembrino": "../imagens/1_esquadrao_gazembrino.png"
  
};

window.ESCUDO_PADRAO = "escudo_default.png";
